### ISSUE TITLE
File write silently fails if `/ext/rfidfuzzer` doesn't exist

### ISSUE THREAD

**Issue by rgmz** [Milk-Cool/fz-em4100-generator#1]
If the `/ext/rfidfuzzer` directory does not exist on your device, for whatever reason, the application will show a successful screen but not file will be written.

<img src="https://github.com/Milk-Cool/fz-em4100-generator/assets/32133502/b91863d4-1f38-40ce-9f69-1bff052194cf" width=250>

Based on my understanding of things, this area of the code should check whether the `/ext/rfidfuzzer` directory exists ([`storage_dir_exists`?](https://github.com/flipperdevices/flipperzero-firmware/blob/76e97b8d35807ea86308b2a45445311226ff64ff/applications/services/storage/storage.h#L193-L200)) and create it if not ([`storage_simply_mkdir`](https://github.com/flipperdevices/flipperzero-firmware/blob/76e97b8d35807ea86308b2a45445311226ff64ff/applications/services/storage/storage.h#L393-L399)).
https://github.com/Milk-Cool/fz-em4100-generator/blob/b518cce4cf3bf5b7a4926255df7117e84d47e84a/key_generator.c#L78

For example:
https://github.com/0xchocolate/flipperzero-wifi-marauder/blob/b437850ec4c6bc74f5f433984c18f3c9c920134b/wifi_marauder_app.c#L97-L102

**Comment by Milk-Cool** [comment]
It expects the RFID Fuzzer app to be installed, which creates this folder. I will fix this as soon as I get home.

**Comment by Milk-Cool** [comment]
![image](https://github.com/Milk-Cool/fz-em4100-generator/assets/43724263/a01750b1-c195-46b3-8d04-e9414571f591)

It should now be fixed. As seen on the image above, it compiles for the latest firmware version.

**Comment by rgmz** [comment]
> It expects the RFID Fuzzer app to be installed, which creates this folder.

I thought so to, yet for some reason it wasn't created. 

Oh well — thanks for sharing this!
